### ISSUE TITLE
processor.php is alerting with status '0.0'

### ISSUE THREAD

**Issue by tamale** [Graphite-Tattle/Tattle#14]
My alert tests for a metrics to be above 30 for warning status and above 50 for error status.  It's consistently between 0 and ~15 most of the time, but I get an alert every valid interval with status '0.0'.

**Comment by g76r** [comment]
Fixes and improvements have been done on alerts processing since opening of this issue.
Therefore I close it, but feel free toreopen it if you still see a bug with v1.1.0.
