### ISSUE TITLE
Special handling for nulls at the very end of a metric.

### ISSUE THREAD

**Issue by otac0n** [Graphite-Tattle/Tattle#33]
When a metric breaches one of the thresholds, an alert is triggered.  When a metric that has been triggered falls back below the threshold, an "all-clear" message is sent out.

I have seen these "all-clear" messages sent out when they should not have been, simply due to the fact that the stats had not yet been published for that metric.

When this happens, the JSON will contain a Null value as the very last entry.

**Comment by g76r** [comment]
I think some users may want for some alerts the current behavior, some other users may want for some other alerts a keepLastValue() behavior (which is more or less @otac0n's pseudocode in #35), and others even transformNull() behavior (as @otac0n states in #33).

The keepLastValue and transformNull value can be implemented by hand on an alert per alert basis, and morover this way one can add a parameter (both keepLastValue and transformNull need one).

Therefore, if nobody else reopens the point and is able to provide a consistent way to enhance this for everyone, I close related issues.

Sorry not to have a better idea.
