### ISSUE TITLE
Brief errors are not triggering notifications.

### ISSUE THREAD

**Issue by otac0n** [Graphite-Tattle/Tattle#35]
We sometimes have errors that last only for a few seconds (CPU usage above the error threshold, for example).  We would like to be notified of these issues, even if they aren't still in error when processor.php is being called.

Rather than checking the last value, we would prefer if Graphite-Tattle checked all values since the last time processor.php was run.

This is related to #33.

**Comment by g76r** [comment]
I'm not sure that ignoring nulls is the right decision since stoping graphite feeding can be an issue that we want to be warned of

**Comment by g76r** [comment]
I think some users may want for some alerts the current behavior, some other users may want for some other alerts a keepLastValue() behavior (which is more or less @otac0n's pseudocode in #35), and others even transformNull() behavior (as @otac0n states in #33).

The keepLastValue and transformNull value can be implemented by hand on an alert per alert basis, and morover this way one can add a parameter (both keepLastValue and transformNull need one).

Therefore, if nobody else reopens the point and is able to provide a consistent way to enhance this for everyone, I close related issues.

Sorry not to have a better idea.
