### ISSUE TITLE
Split the 'Samples' setting

### ISSUE THREAD

**Issue by mlang38** [Graphite-Tattle/Tattle#47]
I use Graphite to store temperatures from sensors once every 15min. As I understood, the "samples" setting is used for 2 purposes : 
- how many samples the moving average is based upon
- how far ago processor.php searches for data in the graphite render request using the "from" parameter

I think the two purposes should be considered separately. With my 15min retention frequency, I must set "samples" to at least 15 to be sure to find data to check. But therefore I'm stuck with a moving average of 15 samples, that I don't want.

**Comment by g76r** [comment]
Hi, I've just merged #52 that should solve the issue by replaceing samples with minutes in moving averages.
