### ISSUE TITLE
Error while trying to run

### ISSUE THREAD

**Issue by ashubham** [Graphite-Tattle/Tattle#56]
I get this error when I try to access the index.php webpage.

PHP Fatal error:  Call to undefined function plugin_listener() in /var/www/Graphite-Tattle/plugins/irccat_plugin.php on line 3

**Comment by g76r** [comment]
Seems odd since it's defined in another Tattle-provided php file.
Did you solve the issue meanwhile or could you give me more info about your config (especialy Tattle version) ?

**Comment by g76r** [comment]
I close the issue due to its age. Feel free to reopen it with more information.
