### ISSUE TITLE
time offset for checks

### ISSUE THREAD

**Issue by phagedorn** [Graphite-Tattle/Tattle#59]
Please add a time based offset for the values which are requestet from graphite.
Usecase:
we calculate different business KPIs/metrics in hadoop with  a interval of 3, 6, 12 and 24 hours.
so we cant use checks based on last x values or minutes.

**Comment by g76r** [comment]
Did you have a look on summarize() graphite function ?
http://graphite.readthedocs.org/en/latest/functions.html#graphite.render.functions.summarize

**Comment by phagedorn** [comment]
Thanks for the reply. Of course i use the summarize() graphite function. But that gives me not the possibility for have an time offset  based on "today" or "yesterday"

**Comment by g76r** [comment]
I'm not sure I well understand what you're doing.
I thought you wanted to compute data on a 3/6/12/24 hours samples, hence I talked about summarize() and though it was enough.
Do you want do display graphs on a dashboard stoped yesterday at midnight without real time ?
Or do you only want time being aligned with midnight to have summarize()'s samples consistent with hours ?
In the second case, a coworker of mine added a "start at midnight" checkbox a few month ago and I merged it into master today.

**Comment by phagedorn** [comment]
Hi there, sorry for the late reply and thanks for the response.
Other than many realtime graphs that we collect in graphite there are many graphs that are processed only once a day. 
![tattle](https://cloud.githubusercontent.com/assets/1391548/8272821/16baf1fe-1853-11e5-9a2e-969348be877f.png)
I want to monitor ob this graphs as well, but cant because there are only data for that time that was processed.

**Comment by g76r** [comment]
Hi,

If I understand well you're processing an external source of actual data (logs...) once a day and write 24h of data into graphite at once.

But I still do not completely understand what you want to do.

You cannot view or alert data that is not yet loaded into the system, therefore what do you want ? to shift the data displayed on the left (as graphite's timeShift function would do) ? to send alert emails for anything that orccured in the last 24h just after having loaded the data (as graphite's summarize(,'max','1d') would) ? something else ?

what would you want tattle to do ? and what tattle module is related (dashboards, threshold checks...) ?

**Comment by g76r** [comment]
I close the issue due to its age. But feel free to reopen it if you have more information.
